# Generated by Django 5.1.1 on 2024-11-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0002_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='description',
            field=models.TextField(),
        ),
    ]
