# Generated by Django 5.1.1 on 2024-11-27 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0003_feedback_date_time_alter_feedback_description'),
        ('lawyerapp', '0003_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.BigIntegerField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default='Pending')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyerapp.services')),
            ],
            options={
                'db_table': 'Book_Services',
            },
        ),
    ]
