# Generated by Django 5.1.1 on 2024-11-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0004_book_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_services',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
