# Generated by Django 5.1.1 on 2024-11-27 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0005_alter_book_services_status'),
        ('lawyerapp', '0003_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('rating', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawyerapp.services')),
            ],
            options={
                'db_table': 'Add_Feedback',
            },
        ),
    ]
