# Generated by Django 5.1.1 on 2024-11-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0006_add_feedback'),
        ('lawyerapp', '0003_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('reply_queries', models.TextField()),
                ('reply_queries_date_time', models.DateTimeField()),
                ('lawyer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lawyerapp.lawyer')),
            ],
            options={
                'db_table': 'Add_Queries',
            },
        ),
    ]
