# Generated by Django 5.1.1 on 2024-11-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0007_add_queries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_queries',
            old_name='lawyer',
            new_name='lawyers',
        ),
    ]
