# Generated by Django 5.1.1 on 2024-11-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0008_rename_lawyer_add_queries_lawyers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_queries',
            name='reply_queries_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
