# Generated by Django 5.1.1 on 2024-11-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0009_alter_add_queries_reply_queries_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_queries',
            name='reply_queries',
            field=models.TextField(default='None'),
        ),
    ]
