# Generated by Django 5.1.6 on 2025-03-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0010_alter_add_queries_reply_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_lawyer',
            name='comments',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_lawyer',
            name='cost',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
