# Generated by Django 5.1.6 on 2025-03-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0011_book_lawyer_comments_book_lawyer_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_lawyer',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book_lawyer',
            name='cost',
            field=models.BigIntegerField(null=True),
        ),
    ]
