# Generated by Django 5.1.6 on 2025-03-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientapp', '0012_alter_book_lawyer_comments_alter_book_lawyer_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_by', models.EmailField(max_length=254)),
                ('file', models.FileField(upload_to='')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientapp.book_lawyer')),
            ],
            options={
                'db_table': 'Manage',
            },
        ),
    ]
